inherit_from: '.rubocop_todo.yml'

# Display reason and how to do it better.
AllCops:
  DisplayStyleGuide: true

# Longer class length
ClassLength:
  Max: 500

# Allow 'some.variable == 0' and others
Style/NumericPredicate:
  Enabled: False
