defaults: &defaults
  # year doesn't matter as long as it is in the past, cronjob creates new date incrementing exactly one year
  begin_study_year: '2009-09-01'

  mongoose_ideal_costs: 0.29
  liquor_time: '16:00'

  intro:
    membership: [1]
    activities: []

  additional_positions:
    committee: ['fotograaf','pr']
    moot: []

  mailchimp:
    # interests are subsection of the mail list
    interests:
      alv: 6b83e19129
      business: 9361be78b3
      mmm: 413462d8c2

    # tags that should be synced using koala, other tags will be ignored
    tags:
      - gratie
      - alumni

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
