# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bd13721adf6c24b29efc41c96d18d5ff81546d4835339bb5a5636770ee3107acebe810b3d0fe3bbcbb7c8cc89d173fcaede74d2064d34389e2cd446a929a3ce

test:
  secret_key_base: 4ba2c13dece7ad97d5d758c932103835300e878d9c2f90050db15d66c925ea0cbc046b8387499759da8797f5413e91a0f568254c52b92cacc0f5a5734b786ce0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
