name: "Build & Test"
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 25838:3306

    env:
      DATABASE_HOST: "127.0.0.1"
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      DATABASE_PORT: 25838

    steps:
    - uses: actions/checkout@v2

    - name: "install Nix"
      uses: cachix/install-nix-action@v11

    - name: "Cache Nix packages"
      uses: cachix/cachix-action@v6
      with:
        name: svsticky-constipated-koala
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
    
    - name: "Cache Yarn packages"
      uses: actions/cache@v2
      with:
        path: node_modules
        key: yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          yarn-

    - name: "Execute Ruby linter"
      run: nix-shell --run "bundle exec rubocop"

    - name: "Check Yarn lockfile"
      run: nix-shell --run "yarn check --frozen-lockfile"

    - name: "Execute Javascript linter"
      run: nix-shell --run "npx prettier -c app/assets/javascripts/*"
    
    - name: "Check for security vulnerabilities"
      run: nix-shell --run "bundle exec brakeman"

    - name: "create database"
      run: nix-shell --run "bundle exec rake db:create --trace"

    - name: Start Redis
      uses: supercharge/redis-github-action@1.1.0
      with:
        redis-version: 5

    - name: "setup database"
      run: nix-shell --run "bundle exec rake db:setup --trace"

    - name: "run tests"
      run: nix-shell --run "bundle exec rake"
