name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    - name: "Execute codechecks"
      run: nix-shell --run "bundle exec rake"
      run: nix-shell --run "npx prettier -c app/assets/javascripts/*"
